### DISCUSSION TITLE
Push notifications when door is unlocked?

### DISCUSSION THREAD

**Discussion by kestena** [BimmerGestalt/AAIdrive#581] [Q&A]
I know that might be a stupid question, but it seems BMW cannot offer it as a feature to their app.

Is there anyway to program the possibility to receive a push notification/sms if a door/window/trunk/bonet is being unlocked? Also, if you left you car unlocked but for some reason it didn't lock automatically, that you get, hey, your car is unlocked...

As said, i suspect it is not possible, but I had to ask.

Thank you!

**Comment by hufman** [comment]
Good morning! AAIdrive itself can not help, because it does not use the cloud ConnectedDrive API.
However, I use Home Assistant and have it set up with ConnectedDrive to do this very thing! I have an automation set up to watch if my door stays unlocked for 15 minutes and send me a text message reminding me to lock it (the software could lock it remotely too, if I wanted). I think having the Home Assistant app on your phone can enable push notification support, but text messages work well enough for me.

The car doesn't push any update to the cloud immediately when anything changes, it just schedules a status update to be uploaded within a few minutes, and so the status from the API is always a bit delayed.

**Reply by kestena** [reply]
This is awesome information. Would you mind sharing how did you set it up?

**Reply by hufman** [reply]
I set up a Home Assistant automation that looks somewhat like this:
```yaml
alias: Car Windows
description: ''
trigger:
  - platform: state
    entity_id:
      - binary_sensor.cooper_se_door_lock_state
      - binary_sensor.cooper_se_lids
      - binary_sensor.cooper_se_windows
    to: 'on'
    for: '00:10:00'
condition:
  - condition: or
    conditions:
      - condition: state
        entity_id: binary_sensor.cooper_se_door_lock_state
        state: 'on'
      - condition: and
        conditions:
          - condition: zone
            entity_id: device_tracker.cooper_se
            zone: zone.home
          - condition: or
            conditions:
              - condition: state
                entity_id: binary_sensor.cooper_se_lids
                state: 'on'
              - condition: state
                entity_id: binary_sensor.cooper_se_windows
                state: 'on'
action:
  - data_template:
      message: >
        Check the car! {% if states('lock.cooper_se_lock') == "unlocked" %} A
        door is {{states('lock.cooper_se_lock')}} or{% else %} The doors look
        locked but{% endif %} a window is open
        (driver:{{state_attr('binary_sensor.cooper_se_windows', 'driverFront')}}
        passenger:{{state_attr('binary_sensor.cooper_se_windows',
        'passengerFront')}}
        sunroof:{{state_attr('binary_sensor.cooper_se_windows', 'moonroof')}})
    service: notify.telegram_walter
mode: single
```
